sonar.projectKey=Keycloak-SPI-Global-Session-Limiter
sonar.projectName=Keycloak SPI Global Session Limiter
sonar.projectVersion=1.0.0

sonar.sources=src/main/java

sonar.java.binaries=target/classes

sonar.host.url=http://localhost:9000
sonar.token=sqp_2a0a19fed2d57c7979235be6f129e362c0964a36

sonar.sourceEncoding=UTF-8